### ISSUE TITLE
Roteiro para apresentação

### ISSUE THREAD

**Issue by thiago-z** [TAF-UC12/UC12_site_cinema#10]
Tópicos para abordar:

1. Apresentação.
- TI05
- UC16
- Apresentar integrantes

2. Falar do que se trata o projeto.
- Explicar o por que de dois sites
- Dizer tecnologias usadas: html, css, javaScript, php, mysql

3. Apresentar site administrativo e relação com o site de cinema.
- Falar do crud e mostrar login no site
- Mostrar funcionamento do site
- Falar sobre facilidade do site para gerenciar conteúdo mesmo pra quem não entende programação
- Explicar funcionamento dos formulários
- Explicar funções do php nos cadastros (inclusão, edição)
- Explicar banco de dados usado (MySQL) e para onde os dados vão

4. Apresentar o site de cinema.
- Mostrar arquivo index.php e explicar como os dados vão para a página inicial
- Explicar funções que puxam noticias para a página home
- Explicar funções que puxam os filmes em cartaz no home
- Explicar funções que puxam noticias para a página de noticias
- Mostrar noticias e falar dos autores na info delas
- Explicar funcionamento da página de filmes

**Comment by andrexsousa** [comment]
posso apresentar esse tópico 2
