### ISSUE TITLE
Banco de dados

### ISSUE THREAD

**Issue by thiago-z** [TAF-UC12/UC12_site_cinema#2]
Preciso saber o andamento do BD, tabelas já foram criadas?
Tabela noticias?
Tabela com ficha técnica dos filmes?

Preciso de uma tabela para comentários, tem que ter: Nome, id, email, data, hora, comentário, e se possível uma foregn key pra linkar com a id da tabela noticia.

E claro, precisamos incluir as informações nas tabelas, o bd precisa ser completado até segunda 1/04, se vc fizer elas eu olho e ajudo a terminar senão vou ter que começar a fazer por conta.

**Comment by andrexsousa** [comment]
fui subir o sql e parece que estou sem acesso apareceu esse erro

Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.

ta no drive.

já criei essas tabelas 
filmes com as informações 
noticias e comentários com as chaves

**Comment by andrexsousa** [comment]
informações como nome, sobrenome, e-mail que  estavam na tabela noticias mandei para a tabela usuários 
então coloquei na tabela usuários a chave para a noticia.
ok?

só não fiz essa parte de niveis de acesso

**Comment by thiago-z** [comment]
Vou verificar seu acesso aqui, quanto tabela de comentarios, pode ser descartada, fiz os comentarios incluindo aquele Discus, mt mais simples e não precisa de BD nele.

**Comment by thiago-z** [comment]
Verifiquei as permissões, tenta mandar denovo.
