### ISSUE TITLE
Rever semântica HTML.

### ISSUE THREAD

**Issue by thiago-z** [TAF-UC12/UC12_site_cinema#4]
# Melhorando a semântica HTML

### Seguindo as boas práticas do html identifiquei alguns pontos do código que precisam ser melhoradas para gerar um código limpo e mais profissional, alguns pontos:

- [x] Indentar o código corretamente.
- [ ] Revisar se tag **main** esta correta no fluxo do código.
- [ ] Revisar se tag **header** esta correta dentro da teg main, senão, mover e corrigir.
- [x] Revisar **divs** com conteúdo que semanticamente deveriam estar dentro de sections, **aside** e **articles**.
- [ ] Revisar o padrão de títulos e o uso incorreto de tags **H1**, **H2**, etc.
- [ ] Comentar o código com informações relevantes para entendimento.
- [ ] Verificar a possibilidade de mover códigos de PHP que geram conteúdo para arquivos separados.

**Comment by andrexsousa** [comment]
Nas noticias a parte do filme relacionado, o poster e o nome do filme aparece outro diferente
porém o resto como os link de ficha técnica e notícias relacionadas estão certas.
![filme relacionado](https://user-images.githubusercontent.com/37748080/39410132-7c57661c-4bc9-11e8-9ff6-759edc02a4a9.PNG)

**Comment by andrexsousa** [comment]
Nas notícias relacionadas de uma notícia: quando vc clica em outra ela fica na mesma página.

**Comment by thiago-z** [comment]
Corrigido, faltava os links no relacionados, agora todos os links relacionados levam a noticia correta e filme correto (os que testei pelo menos).
Já subi o banco corrigido e página noticias com link no relacionados.
