### ISSUE TITLE
Páginas que faltam

### ISSUE THREAD

**Issue by thiago-z** [TAF-UC12/UC12_site_cinema#5]
## Algumas páginas que ainda precisam ser feitas

- [x] **contato.php**: pagina criada mas ainda vazia.
- [x] **filme.php**: criada e em construção (sem ideias de design).

**Aguardando sugestões para concluir essas duas.**

**Comment by andrexsousa** [comment]
nessa pagina de contato vc quer fazer uma página só com informações tipo e-mail entre outros e
ou criar um formulário com nome, e-mail e comentários 
aqueles de mandar sugestões.

**Comment by thiago-z** [comment]
Não sei, talves um form de contato.

**Comment by thiago-z** [comment]
Página de contato feita mas ainda bem simples, não vou criar conexão com bd, será somente para mostrar.
