### ISSUE TITLE
Construindo banco de dados

### ISSUE THREAD

**Issue by thiago-z** [TAF-UC12/UC12_site_cinema#7]
## Deve ser inserido determinada quantidades de dados no banco para dar consistência ao site.

**Informações mínimas divididas por tipos e tópicos:**

Geral
- [x] 30 filmes cadastrados com ficha técnica, img do poster, etc.
- [x] 15 notícias aleatórias.
- [x] 8 artigos aleatórios.
- [x] 10 filmes com url do trailer incluído no banco.

Individual
- [x] 1 filme com pelo menos 4 notícias.
- [x] 1 filme com imagens para galeria de fotos (só para demonstração).

_Favor marcar quando chegar nos objetivos._

**Comment by andrexsousa** [comment]
atualizei o arquivo portal_cinema1.sql 
e a pasta com o img/posters.
tem 40 filmes junto os do jefferson.

**Comment by thiago-z** [comment]
Vou verificar o bd, dps vou excluir esses arquivos .sql e subir um novo atualizado.
