### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by andrexsousa** [TAF-UC12/UC12_site_cinema#8]
- [x] header fixo 

- [x] alterar posição dos itens da header

- [x] verificar cores de fundo da pagina filmes

- [x] verificar os espaçamentos de texto e imagens em outras resoluções

**Comment by thiago-z** [comment]
Header fixo, quanto tento o position: fixed tenho vários erros nas outras divs, do jeito que a página foi montada parece que não vai dar pra fixar...

**Comment by thiago-z** [comment]
Header alterado, aproximei o logo do menu e mudei de posição da busca com as redes.

**Comment by andrexsousa** [comment]
Tem páginas como por exemplo o de lançamentos e contato a header ficam assim.
![header](https://user-images.githubusercontent.com/37748080/39410120-4b7bb764-4bc9-11e8-9750-94f192c42164.PNG)
é deslocado para esquerda.

**Comment by thiago-z** [comment]
Corrigido o float do header dps testar.
